BEGIN;

DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
	id	INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name	VARCHAR(50) NOT NULL UNIQUE,	-- short name
	descr	TEXT,				-- longer description
	price	INT,				-- price in smallest subunits
	img	VARCHAR(128)			-- path to image file
);

DROP TABLE IF EXISTS passwd CASCADE;
CREATE TABLE passwd (
	id	INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name	VARCHAR(32) NOT NULL UNIQUE,	-- login name
	pass	VARCHAR(128)			-- password hash
);

END;
